version: '3.6'
services:
  website:
    image: flumenar-angular
    container_name: website
    restart: always
    ports:
      - "80"
    environment:
      # For nginx-proxy
      - VIRTUAL_HOST=flumenar.com,www.flumenar.com,flumenar.com.ar,www.flumenar.com.ar
      - LETSENCRYPT_HOST=flumenar.com,www.flumenar.com,flumenar.com.ar,www.flumenar.com.ar
      - LETSENCRYPT_EMAIL=federico.davia@gmail.com
      - VIRTUAL_PORT=80
    networks:
      - nginx-proxy

# Networks
networks:
  nginx-proxy:
      external: true
      name: nginx-proxy


