version: '3.6'
services:

  wordpress:
    image: wordpress:latest
    container_name: flumenar
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=flumenar
      - WORDPRESS_TABLE_PREFIX=data_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=VX9LU7vay%GsXlv(ts
      # For nginx-proxy
      - VIRTUAL_HOST=flumenar.com,www.flumenar.com,flumenar.com.ar,www.flumenar.com.ar
      - LETSENCRYPT_HOST=flumenar.com,www.flumenar.com,flumenar.com.ar,www.flumenar.com.ar
      - LETSENCRYPT_EMAIL=federico.davia@gmail.com
      - VIRTUAL_PORT=80
    expose:
      - "80"
    depends_on:
      - mysql
      - phpmyadmin
    restart: always
    networks:
        - flumenar_default
        - nginx-proxy


  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - ./mysql/wordpress:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=VX9LU7vay%GsXlv(ts
      - MYSQL_USER=root
      - MYSQL_PASSWORD=VX9LU7vay%GsXlv(ts
      - MYSQL_DATABASE=flumenar
    restart: always
    networks:
      - flumenar_default

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    restart: always
    ports:
      - "80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=VX9LU7vay%GsXlv(ts
      # For nginx-proxy
      - VIRTUAL_HOST=wp-data.flumenar.com
      - LETSENCRYPT_HOST=wp-data.flumenar.com
      - LETSENCRYPT_EMAIL=federico.davia@gmail.com
      - VIRTUAL_PORT=80
    networks:
      - flumenar_default
      - nginx-proxy

# Airflow

  airflow:
    build: ./airflow/docker
    restart: always
    container_name: airflow
    volumes:
      - ./airflow/mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
      - ./airflow/mnt/airflow/dags:/usr/local/airflow/dags
    ports:
      - "8080"
    environment:
      # For nginx-proxy
      - VIRTUAL_HOST=airflow.deltaanalysis.com
      - LETSENCRYPT_HOST=airflow.deltaanalysis.com
      - LETSENCRYPT_EMAIL=federico.davia@gmail.com
      - VIRTUAL_PORT=8080
    networks:
      - delta_analysis_default
      - nginx-proxy
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10

  mysql-airflow:
    image: mariadb:latest
    container_name: mysql-airflow
    volumes:
      - ./mysql/airflow:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=VX9LU7vay%GsXlv(ts
      - MYSQL_USER=root
      - MYSQL_PASSWORD=VX9LU7vay%GsXlv(ts
      - MYSQL_DATABASE=airflow_data
    restart: always
    networks:
      - delta_analysis_default

  phpmyadmin-airflow:
    depends_on:
      - mysql-airflow
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-airflow
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    restart: always
    ports:
      - "80"
    environment:
      - PMA_HOST=mysql-airflow
      - MYSQL_ROOT_PASSWORD=VX9LU7vay%GsXlv(ts
      # For nginx-proxy
      - VIRTUAL_HOST=datapoints.deltaanalysis.com
      - LETSENCRYPT_HOST=datapoints.deltaanalysis.com
      - LETSENCRYPT_EMAIL=federico.davia@gmail.com
      - VIRTUAL_PORT=80
    networks:
      - delta_analysis_default
      - nginx-proxy

networks:
    delta_analysis_default:
        name: delta_analysis_default
    nginx-proxy:
        external:
            name: nginx-proxy


